name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build with Gradle
      run: |
        sudo apt-get update
        sudo apt-get install --yes openjdk-11-jdk
        VERSION=7.3.3
        wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip -P /tmp
        sudo unzip -d /opt/gradle /tmp/gradle-${VERSION}-bin.zip
        export GRADLE_HOME=/opt/gradle/latest 
        export PATH=${GRADLE_HOME}/bin:${PATH}
        gradle -v
        cd ./NKS/app/
        gradle build
