name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build with Gradle
      run: |
        sudo apt-get update >> log_file 2>&1
        sudo apt-get install --yes openjdk-11-jdk >> log_file 2>&1
        VERSION=6.7.1
        wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip -P /tmp >> log_file 2>&1
        sudo unzip -d /opt/gradle /tmp/gradle-${VERSION}-bin.zip >> log_file 2>&1
        export GRADLE_HOME=/opt/gradle/latest 
        export PATH=${GRADLE_HOME}/bin:${PATH}
        gradle -v
        cd ./NKS/
        gradle build --warning-mode all
